# Generated by Django 4.2.3 on 2023-07-30 08:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=150)),
                ('author_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('subject', models.CharField(max_length=2000)),
                ('book_add_time', models.TimeField(default=datetime.datetime(2023, 7, 30, 8, 57, 2, 888445, tzinfo=datetime.timezone.utc))),
                ('book_add_date', models.DateField(default=datetime.date(2023, 7, 30))),
            ],
            options={
                'unique_together': {('book_name', 'author_name')},
            },
        ),
    ]
