# Generated by Django 4.2.1 on 2023-08-22 10:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0004_issueditem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueditem',
            name='issue_date',
            field=models.DateField(default=datetime.date(2023, 8, 22)),
        ),
    ]
