# Generated by Django 4.2.4 on 2023-08-31 08:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryapp', '0007_remove_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueditem',
            name='issue_date',
            field=models.DateField(default=datetime.date(2023, 8, 31)),
        ),
    ]
